Text can be bold, italic, or strikethrough.

Link to another page.

There should be whitespace between paragraphs.

There should be whitespace between paragraphs. We recommend including a README, or a file with information about your project.
* _layouts
*  _includes

Header 1
This is a normal paragraph following a header. GitHub is a code hosting platform for version control and collaboration. It lets you and others work together on projects from anywhere.

Header 2
This is a blockquote following a header.

When something is important enough, you do it even if the odds are not in your favor.

Header 3
// Javascript code with syntax highlighting.
var fun = function lang(l) {
  dateformat.i18n = require('./lang/' + l)
  return true;
}
# Ruby code with syntax highlighting
GitHubPages::Dependencies.gems.each do |gem, version|
  s.add_dependency(gem, "= #{version}")
end
Header 4
This is an unordered list following a header.
This is an unordered list following a header.
This is an unordered list following a header.
Header 5
This is an ordered list following a header.
This is an ordered list following a header.
This is an ordered list following a header.
Header 6
head1	head two	three
ok	good swedish fish	nice
out of stock	good and plenty	nice
ok	good oreos	hmm
ok	good zoute drop	yumm
There’s a horizontal rule below this.
Here is an unordered list:
Item foo
Item bar
Item baz
Item zip
And an ordered list:
Item one
Item two
Item three
Item four
And a nested list:
level 1 item
level 2 item
level 2 item
level 3 item
level 3 item
level 1 item
level 2 item
level 2 item
level 2 item
level 1 item
level 2 item
level 2 item
level 1 item

theme: jekyll-theme-
# Ustawienia witryny
tytuł : Przestrzeń powietrzna
podtytuł : „ Bezpłatny szablon agencji HTML5 ”
url : „ https://justanother-timetraveller.github.io ”  # podstawowa nazwa hosta i protokół dla Twojej witryny
# baseurl: "/ the / subpath / of / your / site" # Ustaw tę wartość na "", jeśli chcesz, aby witryna była rootem
baseurl : „ / ”
